### ISSUE TITLE
Better sort for dump_uncovered.sh

### ISSUE THREAD

**Issue by bungeman** [google/libfuzzer-bot#2]
It would be nice to replace the 'sort' in freetype/dump_uncovered.sh with something like

sort --field-separator=: --key=1,1 --key=2n,2 --key=3n,3

which would sort the line and column numbers numerically instead of the current lexically.

**Comment by kcc** [comment]
Thanks for the suggestion! Done
We are making a real reporting tool now to replace this one-liner, 
but your suggestion is too simple to not implement now :)
