### ISSUE TITLE
loop_body.sh: line 22: dump_uncovered.sh: Argument list too long

### ISSUE THREAD

**Issue by bungeman** [google/libfuzzer-bot#3]
It looks like the freetype fuzzer ended up with too many files to pass on the command line. Something like
[argument_list_too_long.diff.txt](https://github.com/google/libfuzzer-bot/files/18644/argument_list_too_long.diff.txt)

might work to get around this, but I don't currently have a setup for testing that sort of thing right now.

**Comment by kcc** [comment]
two things here: first, we may already have to trim the corpus. 
second, we need to pass the dir, not the individual files to the coverage collecting process (as I did in pcre and harfbuzz setups). I'll handle this a bit later (today?)

**Comment by kcc** [comment]
Should be fixed now, thanks for reporting! 
Please let me know if the coverage data looks incorrect in any way
